### ISSUE TITLE
Bugzilla request fails when removing security group if it is not set

### ISSUE THREAD

**Issue by wagnerand** [kewisch/mozblocklist#2]
mozblocklist asks whether to remove the security-group regardless if it's set or not.

If it's not set and you answer 'yes', the entire request fails:
```
{ StatusCodeError: 401 - {"documentation":"https://bmo.readthedocs.io/en/latest/api/","error":true,"code":120,"message":"You tried to remove bug 1541010 from the 'blocklist-requests' group, but either this group does not exist, or you are not allowed to remove bugs from this group in the 'Toolkit' product."}
    at new StatusCodeError (/Users/awagner/mozilla/mozblocklist/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/Users/awagner/mozilla/mozblocklist/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/Users/awagner/mozilla/mozblocklist/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/Users/awagner/mozilla/mozblocklist/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.EventEmitter.emit (domain.js:448:20)
    at Request.<anonymous> (/Users/awagner/mozilla/mozblocklist/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:198:13)
    at Request.EventEmitter.emit (domain.js:448:20)
    at IncomingMessage.<anonymous> (/Users/awagner/mozilla/mozblocklist/node_modules/request/request.js:1083:12)
```

**Comment by kewisch** [comment]
Fixed by 20cb0eb4d15e5ef4173214334d53e1a8cf90be32
